# Generated by Django 4.1.5 on 2023-01-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adverseemail_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtSearchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='court_search_status',
            field=models.BooleanField(default=True),
        ),
    ]
