# Generated by Django 4.1.5 on 2023-01-06 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_courtsearchreport_candidate_court_search_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courtsearchreport',
            old_name='title',
            new_name='charges',
        ),
        migrations.AddField(
            model_name='adverseemail',
            name='charges',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email_id',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
