# Generated by Django 4.1.5 on 2023-01-06 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_title_courtsearchreport_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(default=datetime.datetime(2023, 1, 6, 5, 52, 40, 747317, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
